### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by seanmcfeely** [avilum/secimport#8]
**Describe the bug**
ModuleNotFoundError: No module named 'numpy'

**To Reproduce**

```
>>> import secimport
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.10/site-packages/secimport/__init__.py", line 1, in <module>
    from secimport.sandbox_helper import secure_import
  File ".venv/lib/python3.10/site-packages/secimport/sandbox_helper.py", line 13, in <module>
    from numpy import isin
ModuleNotFoundError: No module named 'numpy'
```

**Desktop (please complete the following information):**
 - OS: MacOS M1

**Comment by avilum** [comment]
Fixed in 0.4.3 after this pull request:
https://github.com/avilum/secimport/commit/33ba839ce6853f78aab24c28ef70202205ef27dd

Thanks a lot for opening the issue!
